name: Compiling Problems
description: Report any problems while compiling here
labels: [compiling]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the issue here."
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Command Prompt/Terminal logs (if existing)"
      render: bash
    validations:
      required: false

  - type: dropdown
    id: btarget
    attributes:
      label: "What is your build target?"
      options:
        - "Windows x64"
        - "Windows x32"
        - "Linux"
        - "Mac"
    validations:
      required: true